In [109]:
import numpy as np
import pandas as pd
import sklearn

In [110]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [3]:
iris = load_iris()

In [4]:
iris_data = iris.data # 붓꽃 데이터 feature

In [5]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [6]:
iris_label = iris.target # (품종) 0,1,2로 구분

In [7]:
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df["label"]=iris.target

In [8]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [9]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

In [10]:
df_clf = DecisionTreeClassifier(random_state=11)

In [11]:
df_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

In [12]:
pred = df_clf.predict(X_test)
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [96]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.98

In [14]:
df_clf.fit(iris_data, iris.target)

DecisionTreeClassifier(random_state=11)

In [15]:
pred1 = df_clf.predict(iris_data)

In [16]:
accuracy_score(iris.target,pred1)

1.0

In [17]:
from sklearn.model_selection import KFold

In [18]:
df_clf = DecisionTreeClassifier(random_state=156)

In [19]:
kfold = KFold(n_splits=5)

In [20]:
cv_accuracy = []
iris_data.shape

(150, 4)

In [21]:
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [30]:
n_iter = 0

for train_index, test_index in kfold.split(iris_data):
    x_train, x_test = iris_data[train_index], iris_data[test_index]
    y_train, y_test = iris_label[train_index], iris_label[test_index]
    #학습 및 예측'
    df_clf.fit(x_train, y_train)
    pred = df_clf.predict(x_test)
    n_iter+=1
    # 정확도
    acc = np.round(accuracy_score(y_test,pred),3)
    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    print("\n {0} 교차검증 정확도 : {1}, 학습데이터 크기 {2}, 검증 데이터 크기: {3}" .format(n_iter, acc, train_size, test_size))
    print(" {0} 검증 세트 인덱스 : {1}" .format(n_iter, test_index))
    cv_accuracy.append(acc)
        
print("\n 평균 검증 정확도 확인", np.mean(cv_accuracy))


 1 교차검증 정확도 : 1.0, 학습데이터 크기 120, 검증 데이터 크기: 30
 1 검증 세트 인덱스 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

 2 교차검증 정확도 : 0.967, 학습데이터 크기 120, 검증 데이터 크기: 30
 2 검증 세트 인덱스 : [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

 3 교차검증 정확도 : 0.867, 학습데이터 크기 120, 검증 데이터 크기: 30
 3 검증 세트 인덱스 : [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

 4 교차검증 정확도 : 0.933, 학습데이터 크기 120, 검증 데이터 크기: 30
 4 검증 세트 인덱스 : [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

 5 교차검증 정확도 : 0.733, 학습데이터 크기 120, 검증 데이터 크기: 30
 5 검증 세트 인덱스 : [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

 평균 검증 정확도 확인 0.9000000000000001


In [55]:
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df["label"]=iris.target
iris_df["label"].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [66]:
import sklearn
print(sklearn.__version__)

0.24.2


In [73]:
from sklearn.model_selection import StratifiedKFold

In [91]:
df_clf = DecisionTreeClassifier(random_state=156)

skf = StratifiedKFold(n_splits=3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df["label"]):
    n_iter += 1
    label_train = iris_df["label"].iloc[train_index]
    lbael_test = iris_df["label"].iloc[test_index]
    print("## 교차검증: {0}" .format(n_iter))
    print("학습 레이블 데이터 분포:\n", label_train.value_counts())
    #print("검증 레이블 데이터 분포:\n", label_test.value_counts())

## 교차검증: 1
학습 레이블 데이터 분포:
 2    34
0    33
1    33
Name: label, dtype: int64
## 교차검증: 2
학습 레이블 데이터 분포:
 1    34
0    33
2    33
Name: label, dtype: int64
## 교차검증: 3
학습 레이블 데이터 분포:
 0    34
1    33
2    33
Name: label, dtype: int64


In [114]:
skf = StratifiedKFold(n_splits=3)
n_iter = 0
clf = DecisionTreeClassifier(random_state=156)
cv_accuracy = []


for train_index, test_index in skf.split(iris_df, iris_df["label"]):
    n_iter += 1
    X_train , X_test = iris_data[train_index], iris_data[test_index]
    y_train, y_test = iris_label[train_index], iris_label[test_index]
    #학습 및 예측
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    
    #반복 시마다 정확도 측정
    acc = np.round(accuracy_score(y_test,pred),4)
    cv_accuracy.append(acc)
    print("{0}번 정확도 :".format(n_iter), acc)
    print("검증 데이터 크기 : ", X_train.shape[0])
    print("학습 데이터 크기 {0}" .format(test_index))
    
acc_mean = np.mean(cv_accuracy)
print(acc_mean)

1번 정확도 : 0.98
검증 데이터 크기 :  100
학습 데이터 크기 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
2번 정확도 : 0.94
검증 데이터 크기 :  100
학습 데이터 크기 [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]
3번 정확도 : 0.98
검증 데이터 크기 :  100
학습 데이터 크기 [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]
0.9666666666666667


In [23]:
from sklearn.model_selection import GridSearchCV

In [24]:
grid_parameters = {"max_depth" : [1,2,3], "min_samples_split" : [2,3]}

In [25]:
x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=121)

dtree = DecisionTreeClassifier()

parameters = {"max_depth": [1,2,3], "min_samples_split":[2,3]}

In [26]:
grid_dtree=GridSearchCV(dtree, param_grid=parameters, cv =3, refit = True)

grid_dtree.fit(x_train, y_train)

scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[["params", "mean_test_score", "rank_test_score", "split0_test_score", "split1_test_score", "split2_test_score"]]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

# 3장

### 데이터 인코딩

In [118]:
#레이블 인코딩
from sklearn.preprocessing import LabelEncoder

items = ["TV", "냉장고", "전자레인지", "컴퓨터", "선풍기", "선풍기", "믹서", "믹서"]

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print("인코딩 변환값", labels)
print(encoder.classes_)

인코딩 변환값 [0 1 4 5 3 3 2 2]
['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [125]:
#원-핫 인코딩
 # 1) 변환하기 전 모든 문자열 값 -> 숫자형으로 변환해야함
 # 2) 입력 값으로 2차원 데이터가 필요함.

from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ["TV", "냉장고", "전자레인지", "컴퓨터", "선풍기", "선풍기", "믹서", "믹서"]

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

#2차원 데이터로 변환
labels = labels.reshape(-1,1)

#원-하 인코딩을 적용함
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print("원-핫 인코딩 데이터")
print(oh_labels.toarray())
print("원-핫 인코딩 차원")
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 차원
(8, 6)


In [127]:
df = pd.DataFrame({'items': ["TV", "냉장고", "전자레인지", "컴퓨터", "선풍기", "선풍기", "믹서", "믹서"]})
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0

### 피처스케일링

In [143]:
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

# standatdscalar 
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns = iris.feature_names)
print("feature들의 평균값\n", iris_df_scaled.mean())
print("feature들의 분산 값\n", iris_df_scaled.var())

feature들의 평균값
 sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
feature들의 분산 값
 sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [151]:
# minmaxsxaler
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print("feature들의 최솟값\n", iris_df_scaled.min())
print("feature들의 최대값\n", iris_df_scaled.max())

feature들의 최솟값
 sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature들의 최대값
 sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
